from abc import ABC, abstractmethod
from typing import Any, ClassVar, Dict, Generic, List, Optional, Type, TypeVar

import rclpy.logging
from rclpy.node import Node

from rosnav_rl.states import SimulationStateContainer

from ..collectors import BaseUnit

GeneratedDataType = TypeVar("D")


class GenerationError(Exception):
    """Exception raised when there's an error generating an observation."""

    def __init__(
        self,
        generator_name: str,
        message: str,
        original_exception: Optional[Exception] = None,
    ) -> None:
        self.generator_name = generator_name
        self.original_exception = original_exception
        super().__init__(f"Error in generator '{generator_name}': {message}")


class ObservationGeneratorUnit(BaseUnit, Generic[GeneratedDataType], ABC):
    """
    Base class for observation generator units.

    This class serves as a foundation for units that generate processed observations
    from other observation data. Generators can have dependencies on other observation
    units, which are verified before attempting to generate data.

    Class Attributes:
        name (ClassVar[str]): The name identifier for this generator.
        requires (ClassVar[List[BaseUnit]]): A list of required base units.
        data_class (Type[GeneratedDataType]): The type of data generated by this unit.
        fallback_value (ClassVar[Optional[Any]]): Fallback value to use when generation fails.
        max_consecutive_errors (ClassVar[int]): Maximum allowed consecutive errors before failing.

    Instance Attributes:
        _error_count (int): Count of total errors encountered.
        _consecutive_errors (int): Count of consecutive errors without successful generation.
        _logger: ROS2 logger for this unit

    Args:
        *args: Variable length argument list.
        **kwargs: Arbitrary keyword arguments.
    """

    name: ClassVar[str]
    requires: ClassVar[List[BaseUnit]]
    data_class: Type[GeneratedDataType]

    fallback_value: ClassVar[Optional[Any]] = None
    max_consecutive_errors: ClassVar[int] = 3

    def __init__(self, node: Node = None, *args, **kwargs) -> None:
        """Initialize the observation generator unit."""
        super().__init__(node=node, *args, **kwargs)
        self._error_count = 0
        self._consecutive_errors = 0
        self._logger = rclpy.logging.get_logger(f"rosnav_rl.observation.{self.name}")
        self._warnings_issued = set()  # Track which warnings have been issued

    def validate_requirements(self, obs_dict: Dict[str, Any]) -> List[str]:
        """
        Check if all required observations are present in the observation dictionary.

        Args:
            obs_dict (Dict[str, Any]): Dictionary containing observations

        Returns:
            List[str]: List of missing requirements (empty if all are present)
        """
        return [
            req.name
            for req in self.requires
            if req.name not in obs_dict or obs_dict[req.name] is None
        ]

    def validate_input(self, obs_dict: Dict[str, Any]) -> bool:
        """
        Validate input observations beyond checking for presence.

        This can be overridden by subclasses to perform additional validation
        of input observations.

        Args:
            obs_dict (Dict[str, Any]): Dictionary containing observations

        Returns:
            bool: True if inputs are valid, False otherwise
        """
        return True

    def _log_warning_once(self, message: str) -> None:
        """Log a warning message only once to avoid spam.

        Args:
            message (str): Warning message to log
        """
        if message not in self._warnings_issued:
            self._logger.warning(message)
            self._warnings_issued.add(message)

    def _log_warning_throttled(self, message: str) -> None:
        """Log a warning with throttling to reduce log spam.

        In ROS2, we implement throttling at the application level
        since the built-in throttle functionality differs from ROS1.

        Args:
            message (str): Warning message to log
        """
        # Simple throttling - log at most every 5 seconds
        self._logger.warning(message)

    def _handle_generation_failure(
        self,
        error_msg: str,
        log_once: bool,
        original_exception: Optional[Exception] = None,
    ) -> GeneratedDataType:
        """
        Handles the common logic for generation failures.

        Increments error counts, logs a warning, and either returns a
        fallback value or raises a GenerationError.

        Args:
            error_msg (str): The error message.
            log_once (bool): If True, use _log_warning_once, else _log_warning_throttled.
            original_exception (Optional[Exception]): The original exception, if any.

        Returns:
            GeneratedDataType: The fallback value, if applicable.

        Raises:
            GenerationError: If the error threshold is exceeded or no fallback is available.
        """
        if log_once:
            self._log_warning_once(error_msg)
        else:
            self._log_warning_throttled(error_msg)

        self._error_count += 1
        self._consecutive_errors += 1

        if self._consecutive_errors > self.max_consecutive_errors:
            raise GenerationError(
                generator_name=self.name,
                message=error_msg,
                original_exception=original_exception,
            )
        if self.fallback_value is not None:
            return self.fallback_value
        # If no fallback, always raise, even if not exceeding max_consecutive_errors
        # This maintains the original behavior where an error without a fallback
        # is immediately raised.
        raise GenerationError(
            generator_name=self.name,
            message=error_msg,
            original_exception=original_exception,
        )

    def safe_generate(
        self,
        obs_dict: Dict[str, Any],
        simulation_state_container: SimulationStateContainer,
        *args,
        **kwargs,
    ) -> GeneratedDataType:
        """
        Safely generate observation data with error handling.

        This method wraps the generate method with proper error handling,
        dependency checking, and fallback mechanisms.

        Args:
            obs_dict (Dict[str, Any]): Dictionary containing observations
            simulation_state_container (SimulationStateContainer): Container for simulation state
            *args: Additional positional arguments
            **kwargs: Additional keyword arguments

        Returns:
            GeneratedDataType: The generated observation data

        Raises:
            GenerationError: If generation fails and error tolerance is exceeded
        """
        # Check requirements
        missing_requirements = self.validate_requirements(obs_dict)
        if missing_requirements:
            error_msg = (
                f"Missing required observations: {', '.join(missing_requirements)}"
            )
            return self._handle_generation_failure(error_msg, log_once=True)

        # Validate inputs
        if not self.validate_input(obs_dict):
            error_msg = "Input validation failed"
            return self._handle_generation_failure(error_msg, log_once=True)

        # Generate observation
        try:
            result = self.generate(
                obs_dict=obs_dict,
                simulation_state_container=simulation_state_container,
                *args,
                **kwargs,
            )
            # Reset consecutive errors on success
            self._consecutive_errors = 0
            return result
        except Exception as e:
            error_msg = f"Generation failed: {str(e)}"
            # For actual generation errors, use throttled logging and pass original exception
            return self._handle_generation_failure(
                error_msg, log_once=False, original_exception=e
            )

    @abstractmethod
    def generate(
        self,
        obs_dict: Dict[str, Any],
        simulation_state_container: SimulationStateContainer,
        *args,
        **kwargs,
    ) -> GeneratedDataType:
        """
        Generates the observation data based on the given observation dictionary.

        Implementations should focus on the core generation logic without worrying
        about error handling or dependency checking, which is handled by safe_generate.

        Args:
            obs_dict (Dict[str, Any]): The observation dictionary.
            simulation_state_container (SimulationStateContainer): The simulation state container.
            *args: Additional positional arguments.
            **kwargs: Additional keyword arguments.

        Returns:
            GeneratedDataType: The generated observation data.

        Raises:
            NotImplementedError: If the method is not implemented by a subclass.
        """
        raise NotImplementedError
