[tool.poetry]
name = "rosnav-rl"
version = "0.1.0"
description = "Python Framework for Reinforcement Learning in Robotic Navigation based on ROS"
authors = ["tuananhroman <anh.maxiking@hotmail.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
docutils = "0.20"
torch = "^2.0.0"
wandb = "^0.13.9"
tensorboard = "^2.12.2"
torchdiffeq = "^0.2.3"
diffcp = "^1.0.21"
mpi4py = "^3.1.4"
gputil = "^1.4.0"
tensorboardx = "^2.6"
gym = "^0.22"
opencv-python = "^4.8"
sb3-contrib = "^2.1.0"
shimmy = "^1.3.0"
pygments = "^2.18.0"
stable-baselines3 = "^2.1.0"
gymnasium = "^1.0.0"
ruamel-yaml = "^0.17"


[tool.poetry.group.dev.dependencies]
matplotlib = "^3.0.0"
einops = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = []
select = ["E", "F"]
mccabe = { max-complexity = 10 }
per-file-ignores = {}